CREATE DATABASE IF NOT EXISTS tribaki_database;

USE tribaki_database;

CREATE TABLE weekly_subscription (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name_ VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	is_active BOOLEAN DEFAULT TRUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contact_us (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name_ VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL,
    messages TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin(
	id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'user') DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);